"""Curated meal & exercise database — Indian + international.

Every meal carries full macros (kcal / protein / carbs / fats), a prep
time and an ingredient list, so the engine can build accurate daily plans
and the app can generate a weekly grocery list.

Diet tags used per meal:
    "Vegetarian"     — no meat / fish / eggs
    "Non-Vegetarian" — anything goes
    "Vegan"          — no animal products at all
    "Keto"           — low-carb (roughly < 15 g net carbs per meal)
"""

# ------------------------------------------------------------------ MEALS ---
# Keys: id, name, meal_type, tags, kcal, protein, carbs, fats, prep_min, ingredients
MEALS = [
    # ---------------------------------------------------------- Breakfast ---
    {"id": "masala-oats", "name": "Masala Oats with Vegetables", "meal_type": "Breakfast",
     "tags": ["Vegetarian", "Vegan"], "kcal": 320, "protein": 12, "carbs": 52, "fats": 7,
     "prep_min": 10, "ingredients": ["Rolled oats", "Onion", "Tomato", "Green peas", "Turmeric & spices"]},
    {"id": "poha", "name": "Poha with Peanuts & Green Peas", "meal_type": "Breakfast",
     "tags": ["Vegetarian", "Vegan"], "kcal": 340, "protein": 9, "carbs": 56, "fats": 12,
     "prep_min": 15, "ingredients": ["Flattened rice (poha)", "Peanuts", "Green peas", "Turmeric", "Lemon & curry leaves"]},
    {"id": "paneer-bhurji-roti", "name": "Paneer Bhurji with 2 Whole Wheat Roti", "meal_type": "Breakfast",
     "tags": ["Vegetarian"], "kcal": 430, "protein": 24, "carbs": 34, "fats": 22,
     "prep_min": 20, "ingredients": ["Paneer", "Wheat flour", "Onion", "Tomato", "Spices"]},
    {"id": "egg-omelette-toast", "name": "Egg White Omelette (4 whites + 1 whole) with 2 Toast", "meal_type": "Breakfast",
     "tags": ["Non-Vegetarian"], "kcal": 290, "protein": 24, "carbs": 26, "fats": 9,
     "prep_min": 10, "ingredients": ["Eggs", "Bread", "Spinach", "Onion", "Black pepper"]},
    {"id": "yogurt-berries", "name": "Greek Yogurt Bowl with Berries & Almonds", "meal_type": "Breakfast",
     "tags": ["Vegetarian"], "kcal": 250, "protein": 15, "carbs": 24, "fats": 11,
     "prep_min": 5, "ingredients": ["Greek yogurt", "Mixed berries", "Almonds", "Honey"]},
    {"id": "sprouts-chaat", "name": "Sprouted Moong Chaat", "meal_type": "Breakfast",
     "tags": ["Vegan"], "kcal": 230, "protein": 14, "carbs": 34, "fats": 5,
     "prep_min": 10, "ingredients": ["Sprouted moong", "Onion", "Tomato", "Lemon", "Chaat masala"]},
    {"id": "idli-sambar", "name": "Idli (3) with Sambar & Coconut Chutney", "meal_type": "Breakfast",
     "tags": ["Vegan"], "kcal": 330, "protein": 10, "carbs": 60, "fats": 6,
     "prep_min": 5, "ingredients": ["Idli batter", "Toor dal (sambar)", "Coconut", "Curry leaves"]},
    {"id": "avocado-egg-toast", "name": "Avocado Toast with 2 Boiled Eggs", "meal_type": "Breakfast",
     "tags": ["Non-Vegetarian"], "kcal": 390, "protein": 17, "carbs": 30, "fats": 23,
     "prep_min": 10, "ingredients": ["Bread", "Avocado", "Eggs", "Chili flakes", "Lemon"]},
    {"id": "tofu-scramble", "name": "Tofu Scramble with Multigrain Toast", "meal_type": "Breakfast",
     "tags": ["Vegan"], "kcal": 310, "protein": 20, "carbs": 28, "fats": 13,
     "prep_min": 15, "ingredients": ["Tofu", "Turmeric", "Multigrain bread", "Spinach", "Black salt"]},
    {"id": "vegetable-upma", "name": "Vegetable Upma", "meal_type": "Breakfast",
     "tags": ["Vegetarian", "Vegan"], "kcal": 300, "protein": 8, "carbs": 54, "fats": 8,
     "prep_min": 15, "ingredients": ["Semolina (rava)", "Carrot", "Green peas", "Curry leaves", "Mustard seeds"]},
    {"id": "chia-pudding", "name": "Chia Pudding with Mango & Walnuts", "meal_type": "Breakfast",
     "tags": ["Vegetarian", "Vegan"], "kcal": 280, "protein": 8, "carbs": 32, "fats": 13,
     "prep_min": 5, "ingredients": ["Chia seeds", "Milk or coconut milk", "Mango", "Walnuts"]},
    {"id": "besan-chilla", "name": "Besan Chilla (2) with Green Chutney", "meal_type": "Breakfast",
     "tags": ["Vegetarian", "Vegan"], "kcal": 260, "protein": 12, "carbs": 30, "fats": 10,
     "prep_min": 15, "ingredients": ["Gram flour (besan)", "Spinach", "Green chilies", "Coriander chutney"]},

    # -------------------------------------------------------------- Lunch ---
    {"id": "chicken-rice-salad", "name": "Grilled Chicken Breast with Brown Rice & Salad", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian"], "kcal": 480, "protein": 42, "carbs": 46, "fats": 12,
     "prep_min": 25, "ingredients": ["Chicken breast", "Brown rice", "Cucumber", "Tomato", "Lemon & herbs"]},
    {"id": "paneer-tikka-roti-dal", "name": "Paneer Tikka with 2 Roti & Dal", "meal_type": "Lunch",
     "tags": ["Vegetarian"], "kcal": 540, "protein": 26, "carbs": 50, "fats": 26,
     "prep_min": 30, "ingredients": ["Paneer", "Wheat flour", "Arhar dal", "Yogurt", "Tikka spices"]},
    {"id": "rajma-chawal", "name": "Rajma Chawal with Cucumber Raita", "meal_type": "Lunch",
     "tags": ["Vegetarian"], "kcal": 520, "protein": 18, "carbs": 80, "fats": 11,
     "prep_min": 40, "ingredients": ["Kidney beans (rajma)", "Rice", "Yogurt", "Cucumber", "Onion & tomato"]},
    {"id": "quinoa-buddha-bowl", "name": "Quinoa Buddha Bowl with Chickpeas", "meal_type": "Lunch",
     "tags": ["Vegan"], "kcal": 470, "protein": 16, "carbs": 64, "fats": 17,
     "prep_min": 20, "ingredients": ["Quinoa", "Chickpeas", "Avocado", "Tahini", "Cherry tomatoes"]},
    {"id": "fish-curry-rice", "name": "Fish Curry with Rice (150 g fish)", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian"], "kcal": 460, "protein": 32, "carbs": 50, "fats": 14,
     "prep_min": 30, "ingredients": ["Fish", "Rice", "Coconut", "Curry spices", "Curry leaves"]},
    {"id": "tofu-stirfry-rice", "name": "Tofu Stir-fry with Brown Rice", "meal_type": "Lunch",
     "tags": ["Vegan"], "kcal": 440, "protein": 20, "carbs": 58, "fats": 14,
     "prep_min": 20, "ingredients": ["Tofu", "Brown rice", "Broccoli", "Soy sauce", "Ginger & garlic"]},
    {"id": "dal-makhani-rice", "name": "Dal Makhani with Jeera Rice & Salad", "meal_type": "Lunch",
     "tags": ["Vegetarian"], "kcal": 560, "protein": 20, "carbs": 64, "fats": 24,
     "prep_min": 45, "ingredients": ["Black dal (urad)", "Rice", "Cream", "Butter", "Salad vegetables"]},
    {"id": "egg-curry-roti", "name": "Egg Curry (2 eggs) with 2 Roti", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian"], "kcal": 470, "protein": 20, "carbs": 40, "fats": 26,
     "prep_min": 25, "ingredients": ["Eggs", "Wheat flour", "Onion", "Tomato", "Spices"]},
    {"id": "veg-curry-roti-rice", "name": "Mixed Vegetable Curry with 2 Roti & Small Rice", "meal_type": "Lunch",
     "tags": ["Vegetarian", "Vegan"], "kcal": 490, "protein": 12, "carbs": 72, "fats": 16,
     "prep_min": 30, "ingredients": ["Seasonal vegetables", "Wheat flour", "Rice", "Onion & tomato", "Spices"]},
    {"id": "soya-chunk-curry", "name": "Soya Chunk Curry with Brown Rice", "meal_type": "Lunch",
     "tags": ["Vegan"], "kcal": 450, "protein": 28, "carbs": 54, "fats": 14,
     "prep_min": 25, "ingredients": ["Soya chunks", "Brown rice", "Tomato", "Onion", "Spices"]},

    # ------------------------------------------------------------- Dinner ---
    {"id": "grilled-fish-veg", "name": "Grilled Fish with Lemon & Steamed Vegetables", "meal_type": "Dinner",
     "tags": ["Non-Vegetarian"], "kcal": 380, "protein": 34, "carbs": 14, "fats": 22,
     "prep_min": 20, "ingredients": ["Fish fillet", "Broccoli", "Green beans", "Lemon", "Olive oil"]},
    {"id": "palak-paneer-roti", "name": "Palak Paneer with 1 Roti & Salad", "meal_type": "Dinner",
     "tags": ["Vegetarian"], "kcal": 380, "protein": 18, "carbs": 24, "fats": 24,
     "prep_min": 25, "ingredients": ["Paneer", "Spinach", "Wheat flour", "Cream", "Salad vegetables"]},
    {"id": "veg-khichdi-curd", "name": "Vegetable Khichdi with Curd", "meal_type": "Dinner",
     "tags": ["Vegetarian"], "kcal": 350, "protein": 12, "carbs": 56, "fats": 8,
     "prep_min": 25, "ingredients": ["Rice", "Moong dal", "Seasonal vegetables", "Yogurt (curd)", "Ghee"]},
    {"id": "chicken-soup-salad", "name": "Chicken & Vegetable Soup with Side Salad", "meal_type": "Dinner",
     "tags": ["Non-Vegetarian"], "kcal": 290, "protein": 28, "carbs": 20, "fats": 9,
     "prep_min": 25, "ingredients": ["Chicken", "Mixed vegetables", "Greens", "Black pepper", "Lemon"]},
    {"id": "tofu-broccoli-no-rice", "name": "Tofu & Broccoli Stir-fry (no rice)", "meal_type": "Dinner",
     "tags": ["Vegan", "Keto"], "kcal": 270, "protein": 18, "carbs": 14, "fats": 17,
     "prep_min": 15, "ingredients": ["Tofu", "Broccoli", "Bell pepper", "Olive oil", "Soy sauce"]},
    {"id": "moong-dal-paneer", "name": "Moong Dal Soup with Grilled Paneer (100 g)", "meal_type": "Dinner",
     "tags": ["Vegetarian"], "kcal": 330, "protein": 22, "carbs": 26, "fats": 15,
     "prep_min": 20, "ingredients": ["Moong dal", "Paneer", "Spinach", "Garlic", "Spices"]},
    {"id": "zucchini-noodles-pesto", "name": "Zucchini Noodles with Pesto & Cherry Tomatoes", "meal_type": "Dinner",
     "tags": ["Vegan", "Keto"], "kcal": 310, "protein": 10, "carbs": 16, "fats": 24,
     "prep_min": 15, "ingredients": ["Zucchini", "Pesto", "Cherry tomatoes", "Pine nuts", "Olive oil"]},
    {"id": "cabbage-carrot-roti", "name": "Cabbage & Carrot Sabzi with 2 Roti (light dinner)", "meal_type": "Dinner",
     "tags": ["Vegetarian", "Vegan"], "kcal": 300, "protein": 8, "carbs": 40, "fats": 12,
     "prep_min": 20, "ingredients": ["Cabbage", "Carrot", "Wheat flour", "Onion", "Spices"]},

    # ------------------------------------------------------------- Snacks ---
    {"id": "roasted-makhana", "name": "Roasted Makhana (40 g) with Green Tea", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 140, "protein": 4, "carbs": 26, "fats": 1,
     "prep_min": 5, "ingredients": ["Fox nuts (makhana)", "Black salt", "Lemon", "Green tea"]},
    {"id": "whey-smoothie", "name": "Whey Protein Smoothie with Banana", "meal_type": "Snack",
     "tags": ["Vegetarian"], "kcal": 230, "protein": 24, "carbs": 30, "fats": 3,
     "prep_min": 5, "ingredients": ["Whey protein", "Banana", "Milk or water", "Ice"]},
    {"id": "pb-rice-cakes", "name": "Peanut Butter on Rice Cakes (2)", "meal_type": "Snack",
     "tags": ["Vegetarian", "Vegan"], "kcal": 200, "protein": 8, "carbs": 20, "fats": 11,
     "prep_min": 3, "ingredients": ["Rice cakes", "Peanut butter"]},
    {"id": "sprouts-salad", "name": "Sprouted Moong Salad with Lemon", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 160, "protein": 12, "carbs": 22, "fats": 5,
     "prep_min": 10, "ingredients": ["Sprouted moong", "Onion", "Tomato", "Lemon", "Black pepper"]},
    {"id": "boiled-eggs-cucumber", "name": "2 Boiled Eggs with Cucumber Slices", "meal_type": "Snack",
     "tags": ["Non-Vegetarian", "Keto"], "kcal": 150, "protein": 13, "carbs": 2, "fats": 10,
     "prep_min": 8, "ingredients": ["Eggs", "Cucumber", "Salt & pepper"]},
    {"id": "greek-yogurt-flax", "name": "Greek Yogurt (200 g) with Flaxseeds", "meal_type": "Snack",
     "tags": ["Vegetarian"], "kcal": 130, "protein": 11, "carbs": 10, "fats": 4,
     "prep_min": 2, "ingredients": ["Greek yogurt", "Flaxseeds"]},
    {"id": "hummus-veg-sticks", "name": "Hummus with Cucumber & Carrot Sticks", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 190, "protein": 7, "carbs": 20, "fats": 10,
     "prep_min": 5, "ingredients": ["Chickpeas", "Tahini", "Cucumber", "Carrot", "Lemon"]},
    {"id": "cheese-walnuts", "name": "Cheese Cubes (40 g) with Walnuts (20 g)", "meal_type": "Snack",
     "tags": ["Vegetarian", "Keto"], "kcal": 240, "protein": 8, "carbs": 5, "fats": 22,
     "prep_min": 2, "ingredients": ["Cheese", "Walnuts"]},
    {"id": "keto-paneer-bhurji", "name": "Keto Paneer Bhurji (dry, no gravy)", "meal_type": "Snack",
     "tags": ["Vegetarian", "Keto"], "kcal": 350, "protein": 20, "carbs": 9, "fats": 27,
     "prep_min": 15, "ingredients": ["Paneer", "Butter", "Green chilies", "Kasoori methi", "Spices"]},
    {"id": "egg-bhurji", "name": "Egg Bhurji (3 eggs)", "meal_type": "Snack",
     "tags": ["Non-Vegetarian", "Keto"], "kcal": 310, "protein": 19, "carbs": 7, "fats": 23,
     "prep_min": 10, "ingredients": ["Eggs", "Butter", "Onion", "Green chilies", "Spices"]},
    {"id": "sattu-drink", "name": "Sattu Drink (roasted gram flour) with Lemon", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 210, "protein": 10, "carbs": 32, "fats": 3,
     "prep_min": 5, "ingredients": ["Sattu", "Lemon", "Cumin", "Black salt", "Water"]},

    # ------------------------------------------- higher-calorie options ---
    {"id": "chole-kulcha", "name": "Chole with 2 Kulcha", "meal_type": "Breakfast",
     "tags": ["Vegetarian"], "kcal": 620, "protein": 18, "carbs": 78, "fats": 24,
     "prep_min": 20, "ingredients": ["Chickpeas (chole)", "Kulcha (flour)", "Onion", "Tomato", "Spices"]},
    {"id": "aloo-paratha", "name": "Aloo Paratha (2) with Curd & Butter", "meal_type": "Breakfast",
     "tags": ["Vegetarian"], "kcal": 560, "protein": 12, "carbs": 68, "fats": 26,
     "prep_min": 25, "ingredients": ["Wheat flour", "Potato", "Yogurt", "Butter", "Spices"]},
    {"id": "veg-thali", "name": "Veg Thali: 2 Roti, Dal, Rice, Sabzi, Curd & Papad", "meal_type": "Lunch",
     "tags": ["Vegetarian"], "kcal": 640, "protein": 18, "carbs": 92, "fats": 20,
     "prep_min": 30, "ingredients": ["Wheat flour", "Rice", "Mixed dal", "Seasonal vegetables", "Yogurt", "Papad"]},
    {"id": "paneer-butter-naan", "name": "Paneer Butter Masala with 2 Naan & Rice", "meal_type": "Lunch",
     "tags": ["Vegetarian"], "kcal": 680, "protein": 22, "carbs": 64, "fats": 38,
     "prep_min": 35, "ingredients": ["Paneer", "Naan (flour)", "Rice", "Cream", "Tomato", "Spices"]},
    {"id": "chicken-biryani", "name": "Chicken Biryani (1 plate, ~300 g)", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian"], "kcal": 620, "protein": 30, "carbs": 72, "fats": 22,
     "prep_min": 45, "ingredients": ["Chicken", "Basmati rice", "Yogurt", "Biryani spices", "Fried onion"]},
    {"id": "dal-tadka-roti-rice", "name": "Dal Tadka with 2 Roti & Jeera Rice", "meal_type": "Dinner",
     "tags": ["Vegetarian"], "kcal": 520, "protein": 16, "carbs": 76, "fats": 16,
     "prep_min": 30, "ingredients": ["Arhar dal", "Wheat flour", "Rice", "Ghee", "Spices"]},
    {"id": "egg-fried-rice", "name": "Egg Fried Rice with Veg Manchurian (small)", "meal_type": "Dinner",
     "tags": ["Non-Vegetarian"], "kcal": 560, "protein": 18, "carbs": 74, "fats": 20,
     "prep_min": 25, "ingredients": ["Eggs", "Rice", "Mixed vegetables", "Soy sauce", "Spring onion"]},
    {"id": "trail-mix", "name": "Trail Mix (50 g: almonds, cashews, raisins)", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 290, "protein": 8, "carbs": 24, "fats": 18,
     "prep_min": 2, "ingredients": ["Almonds", "Cashews", "Raisins"]},
    {"id": "peanut-chikki", "name": "Peanut Chikki (2 bars)", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 260, "protein": 8, "carbs": 30, "fats": 12,
     "prep_min": 2, "ingredients": ["Peanuts", "Jaggery"]},
    {"id": "chicken-wrap", "name": "Grilled Chicken Wrap", "meal_type": "Snack",
     "tags": ["Non-Vegetarian"], "kcal": 340, "protein": 24, "carbs": 32, "fats": 12,
     "prep_min": 10, "ingredients": ["Whole wheat tortilla", "Chicken", "Lettuce", "Yogurt dressing"]},

    # ---------------------------------------------------- Keto additions ---
    {"id": "keto-egg-scramble", "name": "Keto Egg & Cheese Scramble (3 eggs)", "meal_type": "Breakfast",
     "tags": ["Non-Vegetarian", "Keto"], "kcal": 380, "protein": 22, "carbs": 6, "fats": 28,
     "prep_min": 10, "ingredients": ["Eggs", "Cheddar cheese", "Butter", "Spinach", "Green chilies"]},
    {"id": "flax-paneer-chilla", "name": "Flaxseed & Paneer Chilla (2, no besan)", "meal_type": "Breakfast",
     "tags": ["Vegetarian", "Keto"], "kcal": 300, "protein": 16, "carbs": 8, "fats": 22,
     "prep_min": 15, "ingredients": ["Flaxseed flour", "Paneer", "Yogurt", "Green chilies", "Spices"]},
    {"id": "keto-chicken-bowl", "name": "Keto Chicken & Avocado Bowl (no rice)", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian", "Keto"], "kcal": 450, "protein": 38, "carbs": 10, "fats": 28,
     "prep_min": 20, "ingredients": ["Chicken breast", "Avocado", "Lettuce", "Olive oil", "Lemon"]},
    {"id": "keto-paneer-bowl", "name": "Keto Paneer & Avocado Bowl (no rice/roti)", "meal_type": "Lunch",
     "tags": ["Vegetarian", "Keto"], "kcal": 480, "protein": 20, "carbs": 14, "fats": 36,
     "prep_min": 15, "ingredients": ["Paneer", "Avocado", "Cucumber", "Walnuts", "Olive oil"]},
    {"id": "keto-egg-cauliflower-rice", "name": "Egg Fried Cauliflower Rice", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian", "Keto"], "kcal": 380, "protein": 18, "carbs": 10, "fats": 30,
     "prep_min": 15, "ingredients": ["Eggs", "Cauliflower rice", "Butter", "Spring onion", "Soy sauce"]},
    {"id": "keto-chicken-stirfry", "name": "Keto Chicken Stir-fry (no rice)", "meal_type": "Dinner",
     "tags": ["Non-Vegetarian", "Keto"], "kcal": 360, "protein": 32, "carbs": 10, "fats": 24,
     "prep_min": 20, "ingredients": ["Chicken", "Bell pepper", "Mushrooms", "Butter", "Soy sauce"]},

    # --------------------------------------------- high-protein options ---
    {"id": "scrambled-eggs-toast", "name": "Scrambled Eggs (4) with Cheese & 2 Toast", "meal_type": "Breakfast",
     "tags": ["Non-Vegetarian"], "kcal": 420, "protein": 26, "carbs": 24, "fats": 24,
     "prep_min": 10, "ingredients": ["Eggs", "Cheddar cheese", "Bread", "Butter", "Black pepper"]},
    {"id": "greek-yogurt-parfait", "name": "Greek Yogurt Parfait (300 g) with Granola & Nuts", "meal_type": "Breakfast",
     "tags": ["Vegetarian"], "kcal": 420, "protein": 25, "carbs": 48, "fats": 14,
     "prep_min": 5, "ingredients": ["Greek yogurt", "Granola", "Almonds", "Honey"]},
    {"id": "soya-bhurji-roti", "name": "Soya Bhurji with 2 Roti", "meal_type": "Breakfast",
     "tags": ["Vegan"], "kcal": 400, "protein": 28, "carbs": 30, "fats": 20,
     "prep_min": 20, "ingredients": ["Soya granules", "Wheat flour", "Onion", "Tomato", "Spices"]},
    {"id": "oats-whey-pb", "name": "Protein Oats with Whey & Peanut Butter", "meal_type": "Breakfast",
     "tags": ["Vegetarian"], "kcal": 450, "protein": 32, "carbs": 52, "fats": 12,
     "prep_min": 8, "ingredients": ["Rolled oats", "Whey protein", "Peanut butter", "Milk", "Banana"]},
    {"id": "tandoori-chicken-roti", "name": "Tandoori Chicken (200 g) with 2 Roti & Salad", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian"], "kcal": 480, "protein": 48, "carbs": 22, "fats": 22,
     "prep_min": 35, "ingredients": ["Chicken", "Wheat flour", "Yogurt", "Tandoori spices", "Salad"]},
    {"id": "fish-tikka-rice", "name": "Fish Tikka (200 g) with Rice & Salad", "meal_type": "Lunch",
     "tags": ["Non-Vegetarian"], "kcal": 460, "protein": 44, "carbs": 42, "fats": 14,
     "prep_min": 30, "ingredients": ["Fish", "Rice", "Yogurt", "Tikka spices", "Salad"]},
    {"id": "soya-chunk-masala", "name": "Soya Chunk Masala with Brown Rice", "meal_type": "Lunch",
     "tags": ["Vegan"], "kcal": 480, "protein": 34, "carbs": 56, "fats": 12,
     "prep_min": 25, "ingredients": ["Soya chunks", "Brown rice", "Onion", "Tomato", "Spices"]},
    {"id": "grilled-chicken-salad", "name": "Grilled Chicken Salad (200 g chicken, no rice)", "meal_type": "Dinner",
     "tags": ["Non-Vegetarian"], "kcal": 350, "protein": 44, "carbs": 10, "fats": 16,
     "prep_min": 20, "ingredients": ["Chicken breast", "Lettuce", "Cucumber", "Olive oil", "Lemon"]},
    {"id": "egg-white-omelette", "name": "Egg White Omelette (6 whites) with Veggies", "meal_type": "Dinner",
     "tags": ["Non-Vegetarian"], "kcal": 220, "protein": 28, "carbs": 8, "fats": 8,
     "prep_min": 10, "ingredients": ["Egg whites", "Spinach", "Mushrooms", "Onion", "Black pepper"]},
    {"id": "cottage-cheese", "name": "Cottage Cheese / Paneer Cubes (150 g) with Chaat Masala", "meal_type": "Snack",
     "tags": ["Vegetarian"], "kcal": 220, "protein": 24, "carbs": 6, "fats": 12,
     "prep_min": 2, "ingredients": ["Paneer or cottage cheese", "Chaat masala", "Lemon"]},
    {"id": "roasted-soya", "name": "Roasted Soya Chunks (50 g dry weight)", "meal_type": "Snack",
     "tags": ["Vegan"], "kcal": 260, "protein": 34, "carbs": 14, "fats": 10,
     "prep_min": 15, "ingredients": ["Soya chunks", "Chili powder", "Lemon", "Black salt"]},
]

# -------------------------------------------------------------- EXERCISES ---
# Keys: id, name, category, muscle, equipment, prescription, kcal, goals, tip
_ALL_GOALS = ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight",
              "Lean Muscle Gain", "Clean Bulk"]

EXERCISES = [
    {"id": "push-ups", "name": "Push-ups", "category": "Strength",
     "muscle": "Chest • Triceps • Shoulders", "equipment": "Bodyweight",
     "prescription": "4 sets × 10–15 reps", "kcal": 60, "goals": _ALL_GOALS,
     "tip": "Keep your body in a straight line — no sagging hips."},
    {"id": "bench-press", "name": "Bench Press", "category": "Strength",
     "muscle": "Chest", "equipment": "Barbell / Dumbbells",
     "prescription": "4 sets × 8–10 reps", "kcal": 90, "goals": _ALL_GOALS,
     "tip": "Lower the bar to mid-chest, elbows at about 45°."},
    {"id": "incline-dumbbell-press", "name": "Incline Dumbbell Press", "category": "Strength",
     "muscle": "Upper Chest", "equipment": "Dumbbells",
     "prescription": "3 sets × 10–12 reps", "kcal": 80, "goals": _ALL_GOALS,
     "tip": "Set the bench to 30–45°."},
    {"id": "bent-over-row", "name": "Bent-Over Dumbbell Row", "category": "Strength",
     "muscle": "Back • Biceps", "equipment": "Dumbbells",
     "prescription": "4 sets × 10–12 reps per arm", "kcal": 80, "goals": _ALL_GOALS,
     "tip": "Hinge at the hips, keep your back flat, pull to your hip."},
    {"id": "lat-pulldown", "name": "Lat Pulldown", "category": "Strength",
     "muscle": "Lats", "equipment": "Cable Machine",
     "prescription": "4 sets × 10–12 reps", "kcal": 85, "goals": _ALL_GOALS,
     "tip": "Pull the bar to your upper chest and squeeze the shoulder blades."},
    {"id": "goblet-squat", "name": "Goblet Squat", "category": "Strength",
     "muscle": "Quads • Glutes", "equipment": "Dumbbell",
     "prescription": "4 sets × 12–15 reps", "kcal": 90, "goals": _ALL_GOALS,
     "tip": "Hold one dumbbell at your chest and sit back between your heels."},
    {"id": "bulgarian-split-squat", "name": "Bulgarian Split Squat", "category": "Strength",
     "muscle": "Quads • Glutes", "equipment": "Bodyweight / Dumbbells",
     "prescription": "3 sets × 10 reps per leg", "kcal": 85, "goals": _ALL_GOALS,
     "tip": "Rear foot elevated on a bench; front knee tracks over the toes."},
    {"id": "romanian-deadlift", "name": "Romanian Deadlift", "category": "Strength",
     "muscle": "Hamstrings • Lower Back", "equipment": "Dumbbells / Barbell",
     "prescription": "4 sets × 10–12 reps", "kcal": 95, "goals": _ALL_GOALS,
     "tip": "Soft knees, hinge at the hips, feel the hamstring stretch."},
    {"id": "walking-lunges", "name": "Walking Lunges", "category": "Strength",
     "muscle": "Quads • Glutes", "equipment": "Bodyweight",
     "prescription": "3 sets × 12 reps per leg", "kcal": 70, "goals": _ALL_GOALS,
     "tip": "Torso upright, front knee bends to about 90°."},
    {"id": "overhead-press", "name": "Overhead Shoulder Press", "category": "Strength",
     "muscle": "Shoulders", "equipment": "Dumbbells",
     "prescription": "4 sets × 10–12 reps", "kcal": 75, "goals": _ALL_GOALS,
     "tip": "Brace your core; do not arch your lower back."},
    {"id": "bicep-curls", "name": "Bicep Curls", "category": "Strength",
     "muscle": "Biceps", "equipment": "Dumbbells",
     "prescription": "3 sets × 12–15 reps", "kcal": 50, "goals": _ALL_GOALS,
     "tip": "Elbows fixed at your sides — no swinging."},
    {"id": "tricep-dips", "name": "Tricep Dips", "category": "Strength",
     "muscle": "Triceps", "equipment": "Bench / Chair",
     "prescription": "3 sets × 12–15 reps", "kcal": 55, "goals": _ALL_GOALS,
     "tip": "Lower until elbows reach about 90°, keep them tucked in."},
    {"id": "face-pulls", "name": "Face Pulls", "category": "Strength",
     "muscle": "Rear Delts • Posture", "equipment": "Cable / Resistance Band",
     "prescription": "3 sets × 15 reps", "kcal": 40, "goals": _ALL_GOALS,
     "tip": "Pull toward your face and rotate your wrists outward at the end."},
    {"id": "glute-bridge", "name": "Glute Bridge", "category": "Strength",
     "muscle": "Glutes • Hamstrings", "equipment": "Bodyweight",
     "prescription": "3 sets × 15 reps", "kcal": 45, "goals": _ALL_GOALS,
     "tip": "Squeeze your glutes hard at the top for 2 seconds."},
    {"id": "jumping-jacks", "name": "Jumping Jacks", "category": "HIIT / Cardio",
     "muscle": "Full Body", "equipment": "Bodyweight",
     "prescription": "4 rounds × 45 seconds", "kcal": 70,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Land softly on the balls of your feet."},
    {"id": "burpees", "name": "Burpees", "category": "HIIT / Cardio",
     "muscle": "Full Body", "equipment": "Bodyweight",
     "prescription": "4 sets × 10 reps", "kcal": 90,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Chest to the floor, explode up."},
    {"id": "mountain-climbers", "name": "Mountain Climbers", "category": "HIIT / Cardio",
     "muscle": "Core • Cardio", "equipment": "Bodyweight",
     "prescription": "4 rounds × 30 seconds", "kcal": 70,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Hips low, drive the knees fast."},
    {"id": "high-knees", "name": "High Knees", "category": "HIIT / Cardio",
     "muscle": "Cardio", "equipment": "Bodyweight",
     "prescription": "4 rounds × 40 seconds", "kcal": 65,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Drive your knees up to hip height."},
    {"id": "jump-rope", "name": "Jump Rope", "category": "HIIT / Cardio",
     "muscle": "Full Body • Calves", "equipment": "Jump Rope",
     "prescription": "5 rounds × 1 minute", "kcal": 80,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Stay on your toes, elbows close to your body."},
    {"id": "brisk-walk", "name": "Brisk Walk (incline treadmill)", "category": "HIIT / Cardio",
     "muscle": "Full Body", "equipment": "Treadmill",
     "prescription": "30 minutes", "kcal": 140, "goals": _ALL_GOALS,
     "tip": "Incline 5–10%, at a pace where talking is slightly hard."},
    {"id": "cycling", "name": "Stationary Cycling", "category": "HIIT / Cardio",
     "muscle": "Legs", "equipment": "Exercise Bike",
     "prescription": "30 minutes", "kcal": 180,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Moderate resistance, cadence 70–90 rpm."},
    {"id": "box-step-ups", "name": "Box Step-ups", "category": "HIIT / Cardio",
     "muscle": "Legs • Cardio", "equipment": "Bench / Step",
     "prescription": "3 sets × 15 reps per leg", "kcal": 75,
     "goals": ["Fat Loss", "Aggressive Fat Loss", "Maintain Weight"],
     "tip": "Drive through your heel, full hip extension at the top."},
    {"id": "plank", "name": "Plank", "category": "Core / Mobility",
     "muscle": "Abs • Back", "equipment": "Bodyweight",
     "prescription": "3 sets × 45–60 seconds", "kcal": 35, "goals": _ALL_GOALS,
     "tip": "Body in a straight line, keep breathing steadily."},
    {"id": "bicycle-crunches", "name": "Bicycle Crunches", "category": "Core / Mobility",
     "muscle": "Obliques • Abs", "equipment": "Bodyweight",
     "prescription": "3 sets × 20 reps", "kcal": 40, "goals": _ALL_GOALS,
     "tip": "Elbow to opposite knee, slow and controlled."},
    {"id": "leg-raises", "name": "Leg Raises", "category": "Core / Mobility",
     "muscle": "Lower Abs", "equipment": "Bodyweight",
     "prescription": "3 sets × 12–15 reps", "kcal": 35, "goals": _ALL_GOALS,
     "tip": "Press your lower back into the floor."},
    {"id": "cat-cow", "name": "Cat-Cow Stretch", "category": "Core / Mobility",
     "muscle": "Spine Mobility", "equipment": "Bodyweight",
     "prescription": "2 sets × 10 reps", "kcal": 15, "goals": _ALL_GOALS,
     "tip": "Move slowly, follow your breath."},
    {"id": "worlds-greatest-stretch", "name": "World's Greatest Stretch", "category": "Core / Mobility",
     "muscle": "Hips • Thoracic Spine", "equipment": "Bodyweight",
     "prescription": "2 sets × 6 reps per side", "kcal": 20, "goals": _ALL_GOALS,
     "tip": "Step into a lunge, rotate your torso toward the front leg."},
    {"id": "foam-rolling", "name": "Foam Rolling / Static Stretching", "category": "Core / Mobility",
     "muscle": "Full Body", "equipment": "Foam Roller",
     "prescription": "10 minutes", "kcal": 20, "goals": _ALL_GOALS,
     "tip": "Roll each muscle group for 30–60 seconds."},
]

EXERCISE_BY_ID = {e["id"]: e for e in EXERCISES}


def is_compatible(meal: dict, diet_pref: str) -> bool:
    """Return True if a meal fits the user's diet preference."""
    tags = meal["tags"]
    if diet_pref == "Non-Vegetarian":
        return True
    if diet_pref == "Vegetarian":
        return "Vegetarian" in tags or "Vegan" in tags
    if diet_pref == "Vegan":
        return "Vegan" in tags
    if diet_pref == "Keto":
        return "Keto" in tags
    return True
